services:
  redis:
    image: redis:latest
    container_name: codegen-redis
    ports:
      - "5252:6379"
    volumes:
      - codegen_redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  codegen_redis_data:
    driver: local