version: "3"

tasks:
  build:
    desc: "Build"
    cmds:
      - go build ./cmd/codegen-service/main.go
  run-dev:
    desc: "Run in dev"
    cmds:
      - CONFIG_PATH=./config/config-dev.yaml ./main
  run-prod:
    desc: "Run in prod"
    cmds:
      - CONFIG_PATH=./config/config.yaml ./main