version: '3'

# launch:
# - task run
tasks:
  build:
    cmds:
      - go build ./cmd/codegen-service/main.go
  run:
    cmds:
      - CONFIG_PATH=./config/config-dev.yaml ./main
    deps:
      - build